// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:24:46

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Example.Final
{
// AddressType represents AddressType
[XmlRoot("AddressType", Namespace = "http://example.com/advanced")]
public class AddressType
{
    [XmlElement]
    public string Street { get; set; }

    [XmlElement]
    public string City { get; set; }

    [XmlElement]
    public string State { get; set; }

    [XmlElement]
    public string ZipCode { get; set; }

    [XmlElement]
    public string Country { get; set; }

}

// ContactType represents ContactType
[XmlRoot("ContactType", Namespace = "http://example.com/advanced")]
public class ContactType
{
    [XmlElement]
    public string Name { get; set; }

    [XmlElement]
    public EmailType Email { get; set; }

    [XmlElement]
    public string Phone { get; set; }

    [XmlElement]
    public AddressType Address { get; set; }

    [XmlAttribute]
    public string Id { get; set; }

    [XmlAttribute]
    public PriorityType Priority { get; set; }

}

// ProjectType represents ProjectType
[XmlRoot("ProjectType", Namespace = "http://example.com/advanced")]
public class ProjectType
{
    [XmlElement]
    public string Title { get; set; }

    [XmlElement]
    public string Description { get; set; }

    [XmlElement]
    public string StartDate { get; set; }

    [XmlElement]
    public string EndDate { get; set; }

    [XmlElement]
    public double Budget { get; set; }

    [XmlElement]
    public List<ContactType> Contacts { get; set; }

    [XmlElement]
    public List<string> Tags { get; set; }

    [XmlAttribute]
    public string ProjectId { get; set; }

    [XmlAttribute]
    public string Status { get; set; }

}

// ProjectListType represents ProjectListType
[XmlRoot("ProjectListType", Namespace = "http://example.com/advanced")]
public class ProjectListType
{
    [XmlElement]
    public List<ProjectType> Projects { get; set; }

    [XmlAttribute]
    public int TotalCount { get; set; }

}

public enum PriorityType
{
    PriorityTypeLow,
    PriorityTypeMedium,
    PriorityTypeHigh,
    PriorityTypeUrgent,
}

}
