// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:24:46

package com.example.final;

import java.util.*;
import java.time.*;
import java.math.*;
import javax.xml.bind.annotation.*;

// AddressType represents AddressType
@XmlRootElement(name = "AddressType")
@XmlType(namespace = "http://example.com/advanced")
public class AddressType {
    @XmlElement
    private String street;
    @XmlElement
    private String city;
    @XmlElement
    private String state;
    @XmlElement
    private String zipCode;
    @XmlElement
    private String country;

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

}

// ContactType represents ContactType
@XmlRootElement(name = "ContactType")
@XmlType(namespace = "http://example.com/advanced")
public class ContactType {
    @XmlElement
    private String name;
    @XmlElement
    private EmailType email;
    @XmlElement
    private String phone;
    @XmlElement
    private AddressType address;
    @XmlAttribute
    private String id;
    @XmlAttribute
    private PriorityType priority;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public EmailType getEmail() {
        return email;
    }

    public void setEmail(EmailType email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public AddressType getAddress() {
        return address;
    }

    public void setAddress(AddressType address) {
        this.address = address;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public PriorityType getPriority() {
        return priority;
    }

    public void setPriority(PriorityType priority) {
        this.priority = priority;
    }

}

// ProjectType represents ProjectType
@XmlRootElement(name = "ProjectType")
@XmlType(namespace = "http://example.com/advanced")
public class ProjectType {
    @XmlElement
    private String title;
    @XmlElement
    private String description;
    @XmlElement
    private String startDate;
    @XmlElement
    private String endDate;
    @XmlElement
    private Double budget;
    @XmlElement
    private List<ContactType> contacts;
    @XmlElement
    private List<String> tags;
    @XmlAttribute
    private String projectId;
    @XmlAttribute
    private String status;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public Double getBudget() {
        return budget;
    }

    public void setBudget(Double budget) {
        this.budget = budget;
    }

    public List<ContactType> getContacts() {
        return contacts;
    }

    public void setContacts(List<ContactType> contacts) {
        this.contacts = contacts;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}

// ProjectListType represents ProjectListType
@XmlRootElement(name = "ProjectListType")
@XmlType(namespace = "http://example.com/advanced")
public class ProjectListType {
    @XmlElement
    private List<ProjectType> projects;
    @XmlAttribute
    private Integer totalCount;

    public List<ProjectType> getProjects() {
        return projects;
    }

    public void setProjects(List<ProjectType> projects) {
        this.projects = projects;
    }

    public Integer getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

}

public enum PriorityType {
    PRIORITYTYPELOW("low"),
    PRIORITYTYPEMEDIUM("medium"),
    PRIORITYTYPEHIGH("high"),
    PRIORITYTYPEURGENT("urgent");

    private final String value;

    PriorityType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}

