// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:24:46

package final

import (
	"encoding/xml"
	"time"
)

// AddressType represents AddressType
type AddressType struct {
	XMLName xml.Name `xml:"http://example.com/advanced AddressType"`
	Street string `xml:"street"`
	City string `xml:"city"`
	State *string `xml:"state,omitempty"`
	ZipCode string `xml:"zipCode"`
	Country string `xml:"country"`
}

// ContactType represents ContactType
type ContactType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ContactType"`
	Name string `xml:"name"`
	Email EmailType `xml:"email"`
	Phone *string `xml:"phone,omitempty"`
	Address AddressType `xml:"address"`
	Id string `xml:"id,attr"`
	Priority *PriorityType `xml:"priority,attr"`
}

// ProjectType represents ProjectType
type ProjectType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ProjectType"`
	Title string `xml:"title"`
	Description *string `xml:"description,omitempty"`
	StartDate string `xml:"startDate"`
	EndDate *string `xml:"endDate,omitempty"`
	Budget *float64 `xml:"budget,omitempty"`
	Contacts []ContactType `xml:"contacts"`
	Tags []string `xml:"tags,omitempty"`
	ProjectId string `xml:"projectId,attr"`
	Status *string `xml:"status,attr"`
}

// ProjectListType represents ProjectListType
type ProjectListType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ProjectListType"`
	Projects []ProjectType `xml:"projects"`
	TotalCount *int32 `xml:"totalCount,attr"`
}

// PriorityType represents
type PriorityType string

// PriorityType enumeration values
const (
	PriorityTypeLow PriorityType = "low"
	PriorityTypeMedium PriorityType = "medium"
	PriorityTypeHigh PriorityType = "high"
	PriorityTypeUrgent PriorityType = "urgent"
)

