// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:19:43

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace models
{
// PersonType represents PersonType
[XmlRoot("PersonType", Namespace = "http://example.com/simple")]
public class PersonType
{
    [XmlElement]
    public string Name { get; set; }

    [XmlElement]
    public int Age { get; set; }

    [XmlElement]
    public string Email { get; set; }

    [XmlElement]
    public StatusType Status { get; set; }

    [XmlAttribute]
    public string Id { get; set; }

}

// TeamType represents TeamType
[XmlRoot("TeamType", Namespace = "http://example.com/simple")]
public class TeamType
{
    [XmlElement]
    public string Name { get; set; }

    [XmlElement]
    public List<PersonType> Members { get; set; }

}

public enum StatusType
{
    StatusTypeActive,
    StatusTypeInactive,
    StatusTypePending,
}

}
