// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:19:43

package models

import (
	"encoding/xml"
	"time"
)

// PersonType represents PersonType
type PersonType struct {
	XMLName xml.Name `xml:"http://example.com/simple PersonType"`
	Name string `xml:"name"`
	Age int32 `xml:"age"`
	Email *string `xml:"email,omitempty"`
	Status StatusType `xml:"status"`
	Id string `xml:"id,attr"`
}

// TeamType represents TeamType
type TeamType struct {
	XMLName xml.Name `xml:"http://example.com/simple TeamType"`
	Name string `xml:"name"`
	Members []PersonType `xml:"members"`
}

// StatusType represents
type StatusType string

// StatusType enumeration values
const (
	StatusTypeActive StatusType = "active"
	StatusTypeInactive StatusType = "inactive"
	StatusTypePending StatusType = "pending"
)

