# Code generated by xsd2code v3.0; DO NOT EDIT.
# Generated on 2025-06-02 00:23:03

from dataclasses import dataclass, field
from typing import List, Optional, Any
from datetime import datetime, date, time, timedelta
from enum import Enum
import xml.etree.ElementTree as ET

# PLCDeviceType represents PLCDeviceType
@dataclass
class PLCDeviceType:
    Name: str
    Enabled: bool
    Temperature: float
    Pressure: float
    Counter: int
    Timestamp: datetime
    Time_of_day: time
    Id: int

