// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-01 23:32:00

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Example.Models
{
// AddressType represents AddressType
[XmlRoot("AddressType", Namespace = "http://example.com/advanced")]
public class AddressType
{
    [XmlElement]
    [JsonPropertyName("street")]
    public string Street { get; set; }

    [XmlElement]
    [JsonPropertyName("city")]
    public string City { get; set; }

    [XmlElement]
    [JsonPropertyName("state,omitempty")]
    public string State { get; set; }

    [XmlElement]
    [JsonPropertyName("zipCode")]
    public string ZipCode { get; set; }

    [XmlElement]
    [JsonPropertyName("country")]
    public string Country { get; set; }

}

// ContactType represents ContactType
[XmlRoot("ContactType", Namespace = "http://example.com/advanced")]
public class ContactType
{
    [XmlElement]
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [XmlElement]
    [JsonPropertyName("email")]
    public EmailType Email { get; set; }

    [XmlElement]
    [JsonPropertyName("phone,omitempty")]
    public string Phone { get; set; }

    [XmlElement]
    [JsonPropertyName("address")]
    public AddressType Address { get; set; }

    [XmlAttribute]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [XmlAttribute]
    [JsonPropertyName("priority,omitempty")]
    public PriorityType Priority { get; set; }

}

// ProjectType represents ProjectType
[XmlRoot("ProjectType", Namespace = "http://example.com/advanced")]
public class ProjectType
{
    [XmlElement]
    [JsonPropertyName("title")]
    public string Title { get; set; }

    [XmlElement]
    [JsonPropertyName("description,omitempty")]
    public string Description { get; set; }

    [XmlElement]
    [JsonPropertyName("startDate")]
    public string StartDate { get; set; }

    [XmlElement]
    [JsonPropertyName("endDate,omitempty")]
    public string EndDate { get; set; }

    [XmlElement]
    [JsonPropertyName("budget,omitempty")]
    public double? Budget { get; set; }

    [XmlElement]
    [JsonPropertyName("contacts")]
    public List<ContactType> Contacts { get; set; }

    [XmlElement]
    [JsonPropertyName("tags,omitempty")]
    public List<string> Tags { get; set; }

    [XmlAttribute]
    [JsonPropertyName("projectId")]
    public string ProjectId { get; set; }

    [XmlAttribute]
    [JsonPropertyName("status,omitempty")]
    public string Status { get; set; }

}

// ProjectListType represents ProjectListType
[XmlRoot("ProjectListType", Namespace = "http://example.com/advanced")]
public class ProjectListType
{
    [XmlElement]
    [JsonPropertyName("projects")]
    public List<ProjectType> Projects { get; set; }

    [XmlAttribute]
    [JsonPropertyName("totalCount,omitempty")]
    public int? TotalCount { get; set; }

}

public enum PriorityType
{
    PriorityTypeLow,
    PriorityTypeMedium,
    PriorityTypeHigh,
    PriorityTypeUrgent,
}

}
