# Code generated by xsd2code v3.0; DO NOT EDIT.
# Generated on 2025-06-02 00:19:43

from dataclasses import dataclass, field
from typing import List, Optional, Any
from datetime import datetime, date, time, timedelta
from enum import Enum
import xml.etree.ElementTree as ET

# AddressType represents AddressType
@dataclass
class AddressType:
    Street: str
    City: str
    State: Optional[str] = None
    ZipCode: str
    Country: str

# ContactType represents ContactType
@dataclass
class ContactType:
    Name: str
    Email: EmailType
    Phone: Optional[str] = None
    Address: AddressType
    Id: str
    Priority: Optional[PriorityType] = None

# ProjectType represents ProjectType
@dataclass
class ProjectType:
    Title: str
    Description: Optional[str] = None
    StartDate: str
    EndDate: Optional[str] = None
    Budget: Optional[float] = None
    Contacts: List[ContactType]
    Tags: Optional[List[str]] = None
    ProjectId: str
    Status: Optional[str] = None

# ProjectListType represents ProjectListType
@dataclass
class ProjectListType:
    Projects: List[ProjectType]
    TotalCount: Optional[int] = None

class PriorityType(Enum):
    PRIORITYTYPELOW = "low"
    PRIORITYTYPEMEDIUM = "medium"
    PRIORITYTYPEHIGH = "high"
    PRIORITYTYPEURGENT = "urgent"

