// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:19:42

package advanced

import (
	"encoding/xml"
	"time"
)

// AddressType represents AddressType
type AddressType struct {
	XMLName xml.Name `xml:"http://example.com/advanced AddressType" json:"-"`
	Street string `xml:"street" json:"street"`
	City string `xml:"city" json:"city"`
	State *string `xml:"state,omitempty" json:"state,omitempty"`
	ZipCode string `xml:"zipCode" json:"zipCode"`
	Country string `xml:"country" json:"country"`
}

// ContactType represents ContactType
type ContactType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ContactType" json:"-"`
	Name string `xml:"name" json:"name"`
	Email EmailType `xml:"email" json:"email"`
	Phone *string `xml:"phone,omitempty" json:"phone,omitempty"`
	Address AddressType `xml:"address" json:"address"`
	Id string `xml:"id,attr" json:"id"`
	Priority *PriorityType `xml:"priority,attr" json:"priority,omitempty"`
}

// ProjectType represents ProjectType
type ProjectType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ProjectType" json:"-"`
	Title string `xml:"title" json:"title"`
	Description *string `xml:"description,omitempty" json:"description,omitempty"`
	StartDate string `xml:"startDate" json:"startDate"`
	EndDate *string `xml:"endDate,omitempty" json:"endDate,omitempty"`
	Budget *float64 `xml:"budget,omitempty" json:"budget,omitempty"`
	Contacts []ContactType `xml:"contacts" json:"contacts"`
	Tags []string `xml:"tags,omitempty" json:"tags,omitempty"`
	ProjectId string `xml:"projectId,attr" json:"projectId"`
	Status *string `xml:"status,attr" json:"status,omitempty"`
}

// ProjectListType represents ProjectListType
type ProjectListType struct {
	XMLName xml.Name `xml:"http://example.com/advanced ProjectListType" json:"-"`
	Projects []ProjectType `xml:"projects" json:"projects"`
	TotalCount *int32 `xml:"totalCount,attr" json:"totalCount,omitempty"`
}

// PriorityType represents
type PriorityType string

// PriorityType enumeration values
const (
	PriorityTypeLow PriorityType = "low"
	PriorityTypeMedium PriorityType = "medium"
	PriorityTypeHigh PriorityType = "high"
	PriorityTypeUrgent PriorityType = "urgent"
)

