// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-02 00:19:42

package com.example.models;

import java.util.*;
import java.time.*;
import java.math.*;
import javax.xml.bind.annotation.*;

// PersonType represents PersonType
@XmlRootElement(name = "PersonType")
@XmlType(namespace = "http://example.com/simple")
public class PersonType {
    @XmlElement
    private String name;
    @XmlElement
    private Integer age;
    @XmlElement
    private String email;
    @XmlElement
    private StatusType status;
    @XmlAttribute
    private String id;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public StatusType getStatus() {
        return status;
    }

    public void setStatus(StatusType status) {
        this.status = status;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

}

// TeamType represents TeamType
@XmlRootElement(name = "TeamType")
@XmlType(namespace = "http://example.com/simple")
public class TeamType {
    @XmlElement
    private String name;
    @XmlElement
    private List<PersonType> members;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<PersonType> getMembers() {
        return members;
    }

    public void setMembers(List<PersonType> members) {
        this.members = members;
    }

}

public enum StatusType {
    STATUSTYPEACTIVE("active"),
    STATUSTYPEINACTIVE("inactive"),
    STATUSTYPEPENDING("pending");

    private final String value;

    StatusType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}

