// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-01 23:27:30

package models

import (
	"encoding/xml"
	"time"
)

// PersonType represents PersonType
type PersonType struct {
	XMLName xml.Name `xml:"http://example.com/simple PersonType" json:"-"`
	Name string `xml:"name" json:"name"`
	Age int32 `xml:"age" json:"age"`
	Email *string `xml:"email,omitempty" json:"email,omitempty"`
	Status StatusType `xml:"status" json:"status"`
	Id string `xml:"id,attr" json:"id"`
}

// TeamType represents TeamType
type TeamType struct {
	XMLName xml.Name `xml:"http://example.com/simple TeamType" json:"-"`
	Name string `xml:"name" json:"name"`
	Members []PersonType `xml:"members" json:"members"`
}

// StatusType represents
type StatusType string

// StatusType enumeration values
const (
	StatusTypeActive StatusType = "active"
	StatusTypeInactive StatusType = "inactive"
	StatusTypePending StatusType = "pending"
)

