# Code generated by xsd2code v3.0; DO NOT EDIT.
# Generated on 2025-06-02 00:07:40

from dataclasses import dataclass, field
from typing import List, Optional, Any
from datetime import datetime, date, time, timedelta
from enum import Enum
import xml.etree.ElementTree as ET

# PersonType represents PersonType
@dataclass
class PersonType:
    Name: str
    Age: int
    Email: Optional[str] = None
    Status: StatusType
    Id: str

# TeamType represents TeamType
@dataclass
class TeamType:
    Name: str
    Members: List[PersonType]

class StatusType(Enum):
    STATUSTYPEACTIVE = "active"
    STATUSTYPEINACTIVE = "inactive"
    STATUSTYPEPENDING = "pending"

