// Code generated by xsd2code v3.0; DO NOT EDIT.
// Generated on 2025-06-01 23:23:59

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Models
{
// PersonType represents PersonType
[XmlRoot("PersonType", Namespace = "http://example.com/simple")]
public class PersonType
{
    [XmlElement]
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [XmlElement]
    [JsonPropertyName("age")]
    public int Age { get; set; }

    [XmlElement]
    [JsonPropertyName("email,omitempty")]
    public string Email { get; set; }

    [XmlElement]
    [JsonPropertyName("status")]
    public StatusType Status { get; set; }

    [XmlAttribute]
    [JsonPropertyName("id")]
    public string Id { get; set; }

}

// TeamType represents TeamType
[XmlRoot("TeamType", Namespace = "http://example.com/simple")]
public class TeamType
{
    [XmlElement]
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [XmlElement]
    [JsonPropertyName("members")]
    public List<PersonType> Members { get; set; }

}

public enum StatusType
{
    StatusTypeActive,
    StatusTypeInactive,
    StatusTypePending,
}

}
